config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

 

  # Defines the root path route ("/")
  # root "posts#index"


  namespace :api do

    resources :wishlists, only:[:create, :destroy]
  


  end

  resources :properties, only: [:show] do
  
    resources :bookings, only: [:new]

  end

end

app/models/amenity.rb
class Amenity < ApplicationRecord
    validates :name, presence: :true
    validates :icon, presence: :true



    has_many :property_amenities, dependent: :destroy


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/property.rb
class Property < ApplicationRecord
    validates :name, presence: :true
    validates :headline, presence: :true
    validates :description, presence: :true
    validates :address_1, presence: :true
    validates :city, presence: :true
    validates :state, presence: :true
    validates :country, presence: :true
  
    monetize :price_cents, allow_nil: true
  
    has_many_attached :images
  
    has_many :reviews, dependent: :destroy

    has_many :property_amenities, dependent: :destroy
    has_many :amenities, through: :property_amenities , source: :amenity ,dependent: :destroy



    has_many :wishlists, dependent: :destroy
    has_many :wishlisted_users, through: :wishlists, source: :user, dependent: :destroy

    has_many :reservations, dependent: :destroy
    has_many :reserved_users, through: :reservations, source: :user, dependent: :destroy
  
    has_rich_text :description 


    def update_average_rating
      average_rating = reviews.average(:final_rating);
      update_column(:average_final_rating, average_rating)
      
    end


    def average_cleanliness_rating
      reviews.average(:cleanliness_rating);
      
    end

    def average_accuracy_rating
      reviews.average(:accuracy_rating);
      
    end

    def average_checkin_rating
      reviews.average(:checkin_rating);
      
    end

    def average_communication_rating
      reviews.average(:communication_rating);
      
    end

    def average_location_rating
      reviews.average(:location_rating);
      
    end

    def average_value_rating
      reviews.average(:value_rating);
      
    end


    def wishlisted_by?(user = nil)

      
      
      return if user.nil?


      wishlisted_users.include?(user) 
      
    
    end

    

 
      def available_dates
        next_reservation = reservations.upcoming_reservations.first
        current_reservation = reservations.current_reservations.first
    
        if current_reservation.nil? && next_reservation.nil?
          # 1. Next -> nil and current -> nul

          Date.tomorrow.strftime('%e %b')..(Date.tomorrow + 30.days).strftime('%e %b')

        elsif current_reservation.nil?
          # 2. 4. Next -> available and current -> nil 

          Date.tomorrow.strftime('%e %b')..next_reservation.checkin_date.strftime('%e %b')

        elsif next_reservation.nil?
          # 3. Next -> nil and current -> available

          current_reservation.checkout_date.strftime('%e %b')..(Date.tomorrow + 30.days).strftime('%e %b')
        
        else
          # 5. Next -> available and current -> available 

          current_reservation.checkout_date.strftime('%e %b')..next_reservation.checkin_date.strftime('%e %b')
        end
      end

    



  end

app/models/property_amenity.rb
class PropertyAmenity < ApplicationRecord
  belongs_to :property
  belongs_to :amenity
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :property

  validates :checkin_date, presence: :true
  validates :checkout_date, presence: :true 

  scope :upcoming_reservations, -> { where("checkin_date > ?", Date.today).order(:checkin_date) }
  scope :current_reservations, -> { where("checkout_date > ?", Date.today).where("checkin_date < ?", Date.today).order(:checkout_date) }

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :property, counter_cache: true

  validates :content, presence: :true
  validates :cleanliness_rating, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 } 
  validates :accuracy_rating, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 } 
  validates :checkin_rating, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 } 
  validates :communication_rating, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 } 
  validates :location_rating, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 } 
  validates :value_rating, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 } 

  after_commit :update_final_rating, on: [:create, :update]

  def update_final_rating
    total_points = cleanliness_rating + 
      accuracy_rating + 
      checkin_rating + 
      communication_rating + 
      location_rating + 
      value_rating

    update_column(:final_rating, total_points.to_f / 6)

    property.update_average_rating
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: :true
  validates :address_1, presence: :true
  validates :city, presence: :true
  validates :state, presence: :true
  validates :country, presence: :true

  has_one_attached :picture


  has_many :wishlists, dependent: :destroy
  has_many :wishlisted_properties, through: :wishlists, source: :user, dependent: :destroy


  has_many :reservations, dependent: :destroy
  has_many :reserved_properties, through: :reservations, source: :property, dependent: :destroy


end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user
  belongs_to :property
end

app/controllers/api/wishlists_controller.rb
module Api
  class WishlistsController < ApplicationController
    protect_from_forgery with: :null_session

    def create
      wishlist = Wishlist.create!(wishlist_params)

      respond_to do |format|
        format.json do
          render json: wishlist.to_json, status: :ok
        end
      end
    end

    def destroy
      wishlist = Wishlist.find(params[:id])
      wishlist.destroy()

      respond_to do |format|
        format.json do
          render json: wishlist.to_json, status: 204
        end
      end
    end

    private

    def wishlist_params
      params.permit(:user_id, :property_id)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @property = Property.find(params[:property_id])
    @checkin_date = Date.parse(params[:checkin_date])
    @checkout_date = Date.parse(params[:checkout_date])

    @total_nights = numberOfNights

     # number of nights
      # base fare
      # service fee
      # total amount


    @base_fare = @property.price * @total_nights
    @service_fee = @base_fare * 0.18
    @total_amount = @base_fare + @service_fee
  end

  private

  def numberOfNights
    checkin_date = Date.parse(params[:checkin_date])
    checkout_date = Date.parse(params[:checkout_date])
    (checkout_date - checkin_date).to_i
  end

  def booking_params
    params.permit(:property_id, :checkin_date, :checkout_date)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
    @properties = Property.all;

  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

    def show
      @property = Property.includes(:reviews).find(params[:id])
      @overall_rating_counts = @property
                                .reviews
                                .group('ROUND(final_rating)')
                                .count
                                .transform_keys(&:to_i)
      
      @overall_rating_counts.default = 0

      upcoming_reservations = @property.reservations.upcoming_reservations.pluck(:checkin_date,:checkout_date)

      @blocked_dates = upcoming_reservations.map { |reservation| [reservation[0].to_s, (reservation[1] - 1.day).to_s] }



    end
    
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/bookings/new.html.erb
<div class="bg-white">


  <main class="pt-4 pb-16">
    
    <div class="mx-auto max-w-2xl px-4 pt-8 sm:px-6 lg:grid lg:max-w-7xl lg:grid-cols-4 lg:grid-rows-[auto,auto,1fr] lg:gap-x-24 lg:px-8">
      <div class="lg:col-span-2">
        <h2 class="text-3xl font-medium leading-6 text-gray-900">Confirm and pay</h2>

        <div class="mt-12">
          <h3 class="text-2xl font-medium text-gray-900">Your trip</h3>
          <div class="flex justify-between mt-4">
            <p class="font-medium">Dates</p>
            <p class="font-medium"><%= @checkin_date.strftime('%e %b') %> - <%= @checkout_date.strftime('%e %b') %></p>
          </div>
        </div>

        <div class="mt-12 border-t border-gray-300 pt-12">
          <h3 class="text-2xl font-medium text-gray-900">Pay with</h3>
        </div>

        <div class="mt-12 border-t border-gray-300 pt-12">
          <h3 class="text-2xl font-medium text-gray-900">Ground rules</h3>
          <p class="mt-6 font-light">We ask every guest to remember a few simple things about what makes a great guest.</p>
          <ul class="font-light list-disc ms-4 mt-4">
            <li>
              Follow the house rules
            </li>
            <li>
              Treat your Host's home like your own
            </li>
          </ul>
        </div>


        <button
          type="submit"
          class="mt-12 flex w-full items-center justify-center rounded-md border border-transparent bg-primary px-8 py-3 text-base font-medium text-white hover:bg-primary-dark focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
        >
          Confirm and pay
        </button>
      </div>

      <div class="mt-4 lg:mt-0 border border-gray-300 lg:col-span-2 rounded-xl p-6 h-min">
        <h2 class="sr-only">Booking information</h2>

        <div class="flex items-center">
          <%= image_tag @property.images[0], class:"w-24 h-24 object-cover rounded-md"%>
          <div class="ml-3 text-black font-medium">
            <div class=><%= @property.name %> - <%= @property.city %>, <%= @property.state %></div>
            <span class="inline-flex items-center pointer-events-none block text-sm text-black mt-2">
              <svg class="mr-1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" aria-hidden="true" role="presentation" focusable="false" style="display: block; height: 12px; width: 12px; fill: currentcolor;">
                <path fill-rule="evenodd" d="m15.1 1.58-4.13 8.88-9.86 1.27a1 1 0 0 0-.54 1.74l7.3 6.57-1.97 9.85a1 1 0 0 0 1.48 1.06l8.62-5 8.63 5a1 1 0 0 0 1.48-1.06l-1.97-9.85 7.3-6.57a1 1 0 0 0-.55-1.73l-9.86-1.28-4.12-8.88a1 1 0 0 0-1.82 0z"></path>
              </svg>
              <%= @property.average_final_rating.round(2) %> (<%= @property.reviews_count %> reviews)
            </span>
          </div>
        </div>

        <div class="relative py-6">
          <div class="absolute inset-0 flex items-center" aria-hidden="true">
            <div class="w-full border-t border-gray-300"></div>
          </div>
        </div>

        <div>
          <h3 class="text-xl font-medium text-gray-900">Price details</h3>
          <div class="flex justify-between font-light mt-6">
            <p><%= humanized_money_with_symbol(@property.price) %> x <%= @total_nights %> night</p>
            <p><%= humanized_money_with_symbol(@base_fare) %></p>
          </div>
          <div class="flex justify-between font-light mt-4">
            <p>Airbnb service fee</p>
            <p><%= humanized_money_with_symbol(@service_fee) %></p>
          </div>
        </div>
        <div class="relative py-6">
          <div class="absolute inset-0 flex items-center" aria-hidden="true">
            <div class="w-full border-t border-gray-300"></div>
          </div>
        </div>
        <div class="flex justify-between font-medium">
          <p>Total</p>
          <p><%= humanized_money_with_symbol(@total_amount) %></p>
        </div>
      </div>
  </main>
</div>

app/views/home/index.html.erb
<div class="bg-white">
  <div class="mx-auto max-w-2xl px-4 sm:px-6 sm:py-8 lg:max-w-7xl lg:px-8">
    <div class="mt-6 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
      <% @properties.each do |property| %>
        <%= link_to property_path(property) do %>
          <div class="group relative cursor-pointer ">
            <div class="relative overflow-hidden rounded-md bg-gray-200">
              <div class="swiper">
                <!-- Additional required wrapper -->
                <div class="swiper-wrapper">
                  <% property.images.each do |image| %>
                    <%= image_tag image, class:"swiper-slide h-full w-full object-cover object-center lg:h-full lg:w-full" %>
                  <% end %>
                </div>
                
                <!-- If we need navigation buttons -->
                <div class="swiper-button-prev"></div>
                <div class="swiper-button-next"></div>
              </div>

              <div class="absolute z-10 right-0 top-0 m-4">
                <svg xmlns="http://www.w3.org/2000/svg" 
                  viewBox="0 0 32 32" 
                  aria-hidden="true" 
                  role="presentation" 
                  focusable="false"
                  class="block h-6 w-6 stroke-white stroke-2 <%= property.wishlisted_by?(current_user) ? 'fill-primary' : 'fill-none' %>"
                  style="overflow: visible;"
                  data-controller="wishlist"
                  data-user-logged-in="<%= user_signed_in? %>"
                  data-property-id="<%= property.id %>"
                  data-user-id="<%= current_user&.id %>"
                  data-wishlist-id="<%= property.wishlists.find_by(user: current_user)&.id %>"
                  data-action="click->wishlist#updateWishlistStatus"
                  data-wishlist-target="icon"
                  data-status="<%= property.wishlisted_by?(current_user) %>"
                  >
                    <path d="M16 28c7-4.73 14-10 14-17a6.98 6.98 0 0 0-7-7c-1.8 0-3.58.68-4.95 2.05L16 8.1l-2.05-2.05a6.98 6.98 0 0 0-9.9 0A6.98 6.98 0 0 0 2 11c0 7 7 12.27 14 17z"></path>
                </svg>
              </div>
            </div>
            <div class="mt-2">
              <div class="flex justify-between">
                <h3 class="text-base font-medium text-gray-700">
                  <%= property.city %>, <%= property.country %>
                </h3>
                <p class="flex items-center text-sm font-light">
                  <svg
                    class="mr-1 block w-3 h-3 fill-current"
                    xmlns="http://www.w3.org/2000/svg" 
                    viewBox="0 0 32 32" 
                    aria-hidden="true" 
                    role="presentation" 
                    focusable="false" 
                  >
                    <path fill-rule="evenodd" d="m15.1 1.58-4.13 8.88-9.86 1.27a1 1 0 0 0-.54 1.74l7.3 6.57-1.97 9.85a1 1 0 0 0 1.48 1.06l8.62-5 8.63 5a1 1 0 0 0 1.48-1.06l-1.97-9.85 7.3-6.57a1 1 0 0 0-.55-1.73l-9.86-1.28-4.12-8.88a1 1 0 0 0-1.82 0z"></path>
                  </svg>
                  <%= (property.average_final_rating).round(2) %>
                </p>
              </div>
              <%# TODO: Add distance from property based on location %>
              <p class="mt-0.5 text-sm text-gray-500"><%= property.available_dates.first %> - <%= property.available_dates.last %></p>
              <p class="mt-0.5 text-sm font-light text-black">
                <span class="font-medium"><%= humanized_money_with_symbol(property.price) %></span> night
              </p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/properties/show.html.erb
<div class="bg-white">
  <main class="pt-4 pb-16">
    <!-- Headline + Share + Wishlist -->
    <div class="flex justify-between mx-auto max-w-2xl px-4 sm:px-6 lg:max-w-7xl lg:px-8 py-2">
      <h1 class="inline text-2xl font-medium leading-7 text-gray-900 sm:truncate"><%= @property.headline %></h1>
      <div class="space-x-1">
        <span 
          data-controller="share"
          data-action="click->share#toggleShareModal"
          class="px-3 pt-2 pb-3 hover:rounded-md hover:bg-gray-100 cursor-pointer"
        >
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" aria-hidden="true" role="presentation" focusable="false" style="display: inline; fill: none; height: 16px; width: 16px; stroke: currentcolor; stroke-width: 2; overflow: visible;"><g fill="none"><path d="M27 18v9a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2v-9M16 3v23V3zM6 13l9.3-9.3a1 1 0 0 1 1.4 0L26 13"></path></g></svg>
          <span class="underline text-sm ms-1">Share</span>
        </span>

        <span 
          class="px-3 pt-2 pb-3 hover:rounded-md hover:bg-gray-100 cursor-pointer"
          data-controller="wishlist"
          data-user-logged-in="<%= user_signed_in? %>"
          data-property-id="<%= @property.id %>"
          data-user-id="<%= current_user&.id %>"
          data-wishlist-id="<%= @property.wishlists.find_by(user: current_user)&.id %>"
          data-action="click->wishlist#updateWishlistStatus"
          data-status="<%= @property.wishlisted_by?(current_user) %>"
        >
          <svg xmlns="http://www.w3.org/2000/svg" 
            viewBox="0 0 32 32" 
            aria-hidden="true" 
            role="presentation" 
            focusable="false"
            class="inline h-4 w-4 stroke-black stroke-2 <%= @property.wishlisted_by?(current_user) ? 'fill-primary' : 'fill-none' %>"
            style="overflow: visible;"
            data-wishlist-target="icon"
            >
              <path d="M16 28c7-4.73 14-10 14-17a6.98 6.98 0 0 0-7-7c-1.8 0-3.58.68-4.95 2.05L16 8.1l-2.05-2.05a6.98 6.98 0 0 0-9.9 0A6.98 6.98 0 0 0 2 11c0 7 7 12.27 14 17z"></path>
          </svg>
          <span 
            class="underline text-sm ms-1"
            data-wishlist-target="text"
          >
            <%= @property.wishlisted_by?(current_user) ? 'Saved' : 'Save' %>
          </span>
        </span>
      </div>
    </div>
    <!-- Image gallery -->
    <div class="mx-auto mt-6 max-w-2xl sm:px-6 lg:grid lg:max-w-7xl lg:grid-cols-4 lg:gap-x-2 lg:px-8">
      <div class="aspect-h-2 aspect-w-3 overflow-hidden lg:rounded-l-lg lg:block col-span-2">
        <%= image_tag @property.images[0], class:"h-full w-full object-cover object-center" %>
      </div>
      <div class="hidden lg:grid lg:grid-cols-1 lg:gap-y-2">
        <div class="aspect-h-2 aspect-w-3 overflow-hidden">
          <%= image_tag @property.images[1], class:"h-full w-full object-cover object-center" %>
        </div>
        <div class="aspect-h-2 aspect-w-3 overflow-hidden">
          <%= image_tag @property.images[2], class:"h-full w-full object-cover object-center" %>
        </div>
      </div>
      <div class="hidden lg:grid lg:grid-cols-1 lg:gap-y-2">
        <div class="aspect-h-2 aspect-w-3 overflow-hidden rounded-tr-lg">
          <%= image_tag @property.images[3], class:"h-full w-full object-cover object-center" %>
        </div>
        <div class="aspect-h-2 aspect-w-3 overflow-hidden rounded-br-lg">
          <%= image_tag @property.images[4], class:"h-full w-full object-cover object-center" %>
        </div>
      </div>
    </div>

    <!-- Property info -->
    <div class="mx-auto max-w-2xl px-4 pt-8 sm:px-6 lg:grid lg:max-w-7xl lg:grid-cols-3 lg:grid-rows-[auto,auto,1fr] lg:gap-x-8 lg:px-8">
      <div class="lg:col-span-2 lg:pr-8">
        <h2 class="text-xl font-medium leading-6 text-gray-900 sm:truncate"><%= @property.name %>, <%= @property.country %></h2>
        <div class="mt-1 font-light">
          <%# TODO: Add checks: check if any value is 0 or 1 or more than 1 %>
          <%= @property.guest_count %> guests · <%= @property.bedroom_count %> bedrooms · <%= @property.bed_count %> beds · <%= @property.bathroom_count %> bathrooms
        </div>
        <div class="mt-1 flex text-base items-center">
          <svg 
            xmlns="http://www.w3.org/2000/svg" 
            viewBox="0 0 32 32" 
            aria-hidden="true" 
            role="presentation" 
            focusable="false"
            class="me-1"
            style="display: inline; height: 16px; width: 16px; fill: currentcolor;"
          >
            <path fill-rule="evenodd" d="m15.1 1.58-4.13 8.88-9.86 1.27a1 1 0 0 0-.54 1.74l7.3 6.57-1.97 9.85a1 1 0 0 0 1.48 1.06l8.62-5 8.63 5a1 1 0 0 0 1.48-1.06l-1.97-9.85 7.3-6.57a1 1 0 0 0-.55-1.73l-9.86-1.28-4.12-8.88a1 1 0 0 0-1.82 0z"></path>
          </svg>
          <% if @property.reviews_count != 0 %>
            <span class="font-medium"><%= (@property.average_final_rating).round(2) %> · <span class="underline"><%= @property.reviews_count %> reviews</span> </span>
          <% else %>
            <span class="font-light">No reviews yet</span>
          <% end %>
        </div>
      </div>

      <!-- Booking Component -->
      <div 
        class="mt-4 lg:mt-0 border rounded-xl p-6 shadow-xl h-auto"
        data-controller="booking"
        data-per-night-price="<%= humanized_money(@property.price) %>"
        data-blocked-dates="<%= @blocked_dates %>"
        >
        <h2 class="sr-only">Booking information</h2>
        <p class="text-lg font-light tracking-tight text-gray-900"><span class="text-2xl font-semibold"><%= humanized_money_with_symbol(@property.price) %></span> night</p>
        <div class="flex mt-6">
          <div class="rounded-l-lg px-3 pb-1.5 pt-2.5 shadow-sm ring-1 ring-inset ring-gray-400 focus-within:ring-2 focus-within:ring-indigo-600">
            <label for="checkin" class="block text-xs font-medium text-gray-900">CHECK-IN</label>
            <input 
              type="text" 
              name="checkin" 
              id="checkin" 
              class="block w-full border-0 p-0 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6"
              value="<%= Date.tomorrow.strftime('%Y-%m-%d') %>"
              data-booking-target="checkin"
              >
          </div>

          <div class="rounded-r-lg px-3 pb-1.5 pt-2.5 shadow-sm ring-1 ring-inset ring-gray-400 focus-within:ring-2 focus-within:ring-indigo-600">
            <label for="checkout" class="block text-xs font-medium text-gray-900">CHECK-OUT</label>
            <input 
              type="text" 
              name="checkout" 
              id="checkout" 
              class="block w-full border-0 p-0 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6"
              value="<%= (Date.tomorrow + 1.day).strftime('%Y-%m-%d') %>"
              data-booking-target="checkout"
              >
          </div>

        </div>
        <button
          data-reserve-property-url="<%= new_property_booking_path(@property) %>"
          type="submit" 
          data-action="click->booking#reserveProperty"
          class="mt-4 flex w-full items-center justify-center rounded-md border border-transparent bg-primary px-8 py-3 text-base font-medium text-white hover:bg-primary-dark focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
        >
          Reserve
        </button>
        <p class="font-light text-center text-sm py-4">You won't be charged yet</p>
        <div class="mt-4">
          <div class="flex justify-between font-light">
            <p><%= humanized_money_with_symbol(@property.price) %> x <span data-booking-target="numberOfNights">1</span> night</p>
            <p><%= currency_symbol %><span data-booking-target="baseFare">0</span></p>
          </div>
          <div class="flex justify-between font-light mt-4">
            <p>Airbnb service fee</p>
            <p><%= currency_symbol %><span data-booking-target="serviceFee">0</span></p>
          </div>
        </div>
        <div class="relative py-6">
          <div class="absolute inset-0 flex items-center" aria-hidden="true">
            <div class="w-full border-t border-gray-300"></div>
          </div>
        </div>
        <div class="flex justify-between font-medium">
          <p>Total</p>
          <p><%= currency_symbol %><span data-booking-target="totalAmount">0</span></p>
        </div>
      </div>

      <div class="py-10 lg:col-span-2 lg:col-start-1 lg:pr-8">
        <!-- Description and details -->
        <div class="border-t border-gray-200 pt-10 mt-4">
          <h3 class="sr-only">Description</h3>

          <div class="space-y-6">
            <p class="text-base text-gray-900"><%= @property.description.to_plain_text.truncate(400) %></p>
            <% if @property.description.to_plain_text.length > 400 %>
              <div 
                class="flex items-center gap-1"
                data-controller="description"
                data-action="click->description#toggleDescriptionModal"
              >
                <span class="font-medium underline">Show more</span>
                <svg viewBox="0 0 18 18" role="presentation" aria-hidden="true" focusable="false" style="height: 12px; width: 12px; display: block; fill: var(--f-k-smk-x);"><path d="m4.29 1.71a1 1 0 1 1 1.42-1.41l8 8a1 1 0 0 1 0 1.41l-8 8a1 1 0 1 1 -1.42-1.41l7.29-7.29z" fill-rule="evenodd"></path></svg>
              </div>

              <%= render 'shared/modal', modalTriggerId: "description", content: 'properties/description_modal', content_params: {description: @property.description} %>
            <% end %>
          </div>
        </div>
      </div>

      <!-- Amenities -->
      <%= render :partial => 'properties/amenities', :locals => {:amenities => @property.amenities} %>
    </div>

    <!-- Reviews -->
    <%= render :partial => 'properties/reviews', :locals => {:property => @property} %>
  </main>
</div>

<%= render 'shared/modal', modalTriggerId: "share", content: 'properties/share_modal', content_params: { property: @property } %>